server:
    verbosity: 1
    interface: 0.0.0.0
    port: 53
    do-ip4: yes
    do-udp: yes
    do-tcp: yes
    access-control: 172.20.0.0/12 allow
    access-control: 10.202.0.0/16 allow
    access-control: 127.0.0.0/8 allow
    cache-max-ttl: 86400
    cache-min-ttl: 0
    neg-cache-size: 4m
    hide-identity: yes
    hide-version: yes
    local-zone: "dc2.local." static
    local-data: "web1.dc2.local. IN A 172.20.2.10"
    local-data: "web2.dc2.local. IN A 172.20.2.11"
    local-data: "web3.dc2.local. IN A 172.20.2.12"
    local-data: "dns1.dc2.local. IN A 172.20.2.20"
    local-data: "dns2.dc2.local. IN A 172.20.2.21"
    local-data: "samba.dc2.local. IN A 172.20.2.30"

forward-zone:
    name: "."
    forward-addr: 8.8.8.8
    forward-addr: 1.1.1.1
