frr version 9.1
frr defaults traditional
hostname spine1
no ipv6 forwarding
!
interface eth1
 ip address 172.16.0.0/31
 ip ospf area 0
 ip ospf network point-to-point
!
interface eth2
 ip address 172.16.0.2/31
 ip ospf area 0
 ip ospf network point-to-point
!
interface eth3
 ip address 172.16.0.4/31
 ip ospf area 0
 ip ospf network point-to-point
!
interface lo
 ip address 172.16.255.1/32
 ip ospf area 0
 ip ospf passive
!
router ospf
 ospf router-id 172.16.255.1
 passive-interface lo
!
! BGP pour EVPN (overlay, unchanged)
router bgp 65100
 bgp router-id 172.16.255.1
 neighbor 172.16.255.11 remote-as 65001
 neighbor 172.16.255.11 update-source lo
 neighbor 172.16.255.12 remote-as 65002
 neighbor 172.16.255.12 update-source lo
 neighbor 172.16.255.13 remote-as 65003
 neighbor 172.16.255.13 update-source lo
 !
 address-family l2vpn evpn
  neighbor 172.16.255.11 activate
  neighbor 172.16.255.11 route-reflector-client
  neighbor 172.16.255.11 next-hop-unchanged
  neighbor 172.16.255.12 activate
  neighbor 172.16.255.12 route-reflector-client
  neighbor 172.16.255.12 next-hop-unchanged
  neighbor 172.16.255.13 activate
  neighbor 172.16.255.13 route-reflector-client
  neighbor 172.16.255.13 next-hop-unchanged
 exit-address-family
!
line vty
!
end
