frr version 9.1
frr defaults traditional
hostname leaf2
no ipv6 forwarding
!
interface eth1
 description spine1
 ip address 172.16.0.3/31
!
interface eth2
 description spine2
 ip address 172.16.0.9/31
!
interface lo
 ip address 172.16.255.12/32
!
router bgp 65002
 bgp router-id 172.16.255.12
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 !
 neighbor SPINES peer-group
 neighbor SPINES update-source lo
 neighbor SPINES bfd
 !
 neighbor 172.16.255.1 peer-group SPINES
 neighbor 172.16.255.1 remote-as 65100
 neighbor 172.16.255.2 peer-group SPINES
 neighbor 172.16.255.2 remote-as 65100
 !
 address-family ipv4 unicast
  network 172.16.255.12/32
  neighbor SPINES activate
  neighbor SPINES next-hop-self
  neighbor SPINES soft-reconfiguration inbound
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor SPINES activate
  advertise-all-vni
 exit-address-family
!
ip route 172.16.255.1/32 172.16.0.2
ip route 172.16.255.2/32 172.16.0.8
!
line vty
!
end
