frr version 10.6.1
frr defaults traditional
hostname leaf3
no ipv6 forwarding
agentx
service integrated-vtysh-config
!
ip route 172.16.255.1/32 172.16.0.4
ip route 172.16.255.2/32 172.16.0.10
!
interface eth1
 description spine1
 ip address 172.16.0.5/31
exit
!
interface eth2
 description spine2
 ip address 172.16.0.11/31
exit
!
interface lo
 ip address 172.16.255.13/32
exit
!
router bgp 65000
 bgp router-id 172.16.255.13
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 neighbor 172.16.255.1 remote-as 65000
 neighbor 172.16.255.1 update-source lo
 neighbor 172.16.255.2 remote-as 65000
 neighbor 172.16.255.2 update-source lo
 !
 address-family ipv4 unicast
  network 172.16.255.13/32
  maximum-paths ibgp 2
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 172.16.255.1 activate
  neighbor 172.16.255.2 activate
  advertise-all-vni
 exit-address-family
exit
!
