frr defaults traditional
hostname spine1
no ipv6 forwarding
!
interface eth1
 description leaf1
 ip address 172.16.0.0/31
!
interface eth2
 description leaf2
 ip address 172.16.0.2/31
!
interface eth3
 description leaf3
 ip address 172.16.0.4/31
!
interface lo
 ip address 172.16.255.1/32
!
! iBGP — spine1 est Route Reflector (overlay EVPN + distribution loopbacks)
router bgp 65000
 bgp router-id 172.16.255.1
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 neighbor 172.16.255.11 remote-as 65000
 neighbor 172.16.255.11 update-source lo
 neighbor 172.16.255.12 remote-as 65000
 neighbor 172.16.255.12 update-source lo
 neighbor 172.16.255.13 remote-as 65000
 neighbor 172.16.255.13 update-source lo
 !
 address-family ipv4 unicast
  network 172.16.255.1/32
  neighbor 172.16.255.11 activate
  neighbor 172.16.255.11 route-reflector-client
  neighbor 172.16.255.11 next-hop-self force
  neighbor 172.16.255.12 activate
  neighbor 172.16.255.12 route-reflector-client
  neighbor 172.16.255.12 next-hop-self force
  neighbor 172.16.255.13 activate
  neighbor 172.16.255.13 route-reflector-client
  neighbor 172.16.255.13 next-hop-self force
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 172.16.255.11 activate
  neighbor 172.16.255.11 route-reflector-client
  neighbor 172.16.255.12 activate
  neighbor 172.16.255.12 route-reflector-client
  neighbor 172.16.255.13 activate
  neighbor 172.16.255.13 route-reflector-client
 exit-address-family
!
! Bootstrap : joindre les loopbacks des leafs pour monter l'iBGP
ip route 172.16.255.11/32 172.16.0.1
ip route 172.16.255.12/32 172.16.0.3
ip route 172.16.255.13/32 172.16.0.5
!
line vty
!
