# Ansible inventory created from ['/root/SAE_devCloud_D01/topology.yml', 'package:topology-defaults.yml']
#

all:
  hosts: {}
as65001:
  hosts:
    leaf1: {}
    leaf2: {}
    leaf3: {}
    spine1: {}
    spine2: {}
custom_configs:
  hosts: {}
daemons:
  hosts: {}
frr:
  hosts:
    leaf1:
      ansible_host: clab-devcloudevpn-leaf1
      id: 3
    leaf2:
      ansible_host: clab-devcloudevpn-leaf2
      id: 4
    leaf3:
      ansible_host: clab-devcloudevpn-leaf3
      id: 5
    spine1:
      ansible_host: clab-devcloudevpn-spine1
      id: 1
    spine2:
      ansible_host: clab-devcloudevpn-spine2
      id: 2
leafs:
  hosts:
    leaf1: {}
    leaf2: {}
    leaf3: {}
linux:
  hosts:
    annuaire:
      ansible_host: clab-devcloudevpn-annuaire
      id: 7
    dns1:
      ansible_host: clab-devcloudevpn-dns1
      id: 8
    web1:
      ansible_host: clab-devcloudevpn-web1
      id: 6
    web2:
      ansible_host: clab-devcloudevpn-web2
      id: 9
modules:
  hosts:
    annuaire: {}
    dns1: {}
    leaf1: {}
    leaf2: {}
    leaf3: {}
    spine1: {}
    spine2: {}
    web1: {}
    web2: {}
netlab_no_collect:
  hosts:
    annuaire: {}
    dns1: {}
    web1: {}
    web2: {}
netlab_no_reload:
  hosts:
    annuaire: {}
    dns1: {}
    web1: {}
    web2: {}
services:
  hosts:
    annuaire: {}
    dns1: {}
    web1: {}
    web2: {}
spines:
  hosts:
    spine1: {}
    spine2: {}
unprovisioned:
  hosts: {}
