# snmpd — leafs & spines FRR (SAE DevCloud 4D01)
# IF-MIB (compteurs trafic) + AgentX maitre (FRR -> BGP4-MIB)

agentaddress udp:10161

# AgentX : snmpd = maitre, FRR bgpd/zebra = sous-agents
master agentx
agentXSocket tcp:127.0.0.1:705

# Acces lecture seule
rocommunity public

# Infos systeme
sysLocation  DC1 - SAE DevCloud 4D01
sysContact   houssam@dc1.local
sysServices  72
