# snmpd — leafs & spines FRR (SAE DevCloud 4D01)
# IF-MIB (compteurs trafic) + AgentX (FRR bgpd/zebra -> BGP4-MIB / routes)
# Port 10161 : le 161 (privilegie) est refuse dans le netns containerlab.

agentaddress udp:10161

# AgentX via socket Unix (le port TCP 705 est aussi privilegie -> evite)
master agentx
agentXSocket /var/agentx/master

# Acces lecture seule
rocommunity public

# Infos systeme
sysLocation  DC1 - SAE DevCloud 4D01
sysContact   houssam@dc1.local
sysServices  72
