# Unbound DNS — DC1
server:
    verbosity: 1
    interface: 0.0.0.0
    port: 53
    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    # Obligatoire dans un conteneur Alpine (sinon crash immédiat)
    username: ""
    chroot: ""

    # Réseau autorisé
    access-control: 172.20.0.0/12 allow
    access-control: 10.202.0.0/16 allow
    access-control: 127.0.0.0/8 allow

    # Cache
    cache-max-ttl: 86400
    cache-min-ttl: 0
    neg-cache-size: 4m

    # Sécurité
    hide-identity: yes
    hide-version: yes

    # Zone locale dc1.local
    local-zone: "dc1.local." static
    local-data: "web1.dc1.local. IN A 172.20.1.10"
    local-data: "web2.dc1.local. IN A 172.20.1.11"
    local-data: "web3.dc1.local. IN A 172.20.1.12"
    local-data: "web.dc1.local. IN A 172.20.1.40"
    local-data: "dns1.dc1.local. IN A 172.20.1.20"
    local-data: "dns2.dc1.local. IN A 172.20.1.21"
    local-data: "haproxy.dc1.local. IN A 172.20.1.40"
    local-data: "samba.dc1.local. IN A 172.20.1.30"
    local-data: "monitoring.dc1.local. IN A 172.20.1.50"

forward-zone:
    name: "."
    forward-addr: 8.8.8.8
    forward-addr: 1.1.1.1
