#!/bin/bash
set -e
set -x

# VLAN 10 / VNI 1010: services existants, dns1 reste sur eth3.
if [ ! -e /sys/devices/virtual/net/vlan10 ]; then
  ip link add vlan10 type bridge
  ip link set dev vlan10 address ca:f4:00:05:00:00
  ip addr flush dev vlan10
  sysctl -w net.ipv6.conf.vlan10.disable_ipv6=1
fi
ip link set dev eth3 master vlan10
ip link set dev vlan10 up

# VLAN 40 / VNI 1040: reseau binomes 10.192.1.0/24, web2 sur eth4.
ip link set dev eth4 nomaster 2>/dev/null || true
if [ ! -e /sys/devices/virtual/net/Vlan40 ]; then
  ip link add Vlan40 type bridge
  ip link set dev Vlan40 address ca:f4:00:28:00:00
  sysctl -w net.ipv6.conf.Vlan40.disable_ipv6=1
fi
ip link set Vlan40 type bridge stp_state 0
ip link set dev eth4 master Vlan40
ip link set dev Vlan40 up
